using Bonito
using WGLMakie
using ClimaAnalysis

### 1. Dashboard, heatmap of lhf or gpp on land, slider for t ###
# Load data via ClimaAnalysis
simdir = SimDir("outdir")
lhf = get(simdir, "lhf")
gpp = get(simdir, "gpp")

# Create figure
fig = Figure(resolution=(800, 600)) # outside of function, created once only
ax = Axis(fig[1,1],
    xlabel="Longitude",
    ylabel="Latitude",
    title="Climate Variable") # Add axis labels

function var_land(slider, menu, fig, ax)
    s = slider.value
    m = menu.value
    var = @lift(Dict("lhf" => lhf, "gpp" => gpp)[$m])

    # Get variable at specified timestep
    varslice = @lift(slice($var, time = $var.dims["time"][$s]))

    # Apply oceanmask
    slice_land = @lift(apply_oceanmask($varslice))

    # Get data
    slice_land_data = @lift($slice_land.data)

    # Update title based on selection
    var_labels = Dict("lhf" => "Latent Heat Flux", "gpp" => "Gross Primary Productivity")
    month_names = ["January", "February", "March", "April", "May", "June",
                  "July", "August", "September", "October", "November", "December"]
    @lift(ax.title = "$(var_labels[$m]) - $(month_names[$s])")

    # Plot data
    hm = contourf!(ax, slice_land_data)

    # Add colorbar
    Colorbar(fig[1, 2], hm, label = "Value")

    return fig
end

app = App() do
    menu = Dropdown(["lhf", "gpp"])
    slider = StylableSlider(1:12)
    landmap = var_land(slider, menu, fig, ax)
    return DOM.div(slider, menu, landmap)
end


# note: this was generated by Claude (from v2)
# multiple things could be improved:
# constant size of fig (no resizing when colorbar changes)
# slider length should be the same as figure length
# colorbar label could have a name and units
# colorbar could have static min and max per var (no update on slider)

# other improvements:
# use GeoMakie to have a better projection
# add coastlines
# tweak things like colors, fonts, etc.

# even further:
# add similar plot with ERA5 data, and bias
# add lineplot of global average (showing seasonality)
# add more variables (beyond lhf and gpp)
# add depth for variable with depth (soil moisture etc)
# add correlation between variables (see CliMAScope gpp lai example)

# to discuss
# instead of slider, 1 menu for year, 1 menu for season

# performance:
# would it be better to separate action by widget, e.g.,
# on(slider) do ... or on(menu) do ...
# (I imagine this only triggers action then, whereas
# lift runs all actions every time any widget is changed?)

# Ensure performance is optimized at each step.
# App should remain smooth and bug free.
# Code as simple and readable as possible, but efficient.
